### PR TITLE
Fix issue 2943 - UnsolvedSymbolException thrown on Stream.<func>(<some lambda>)

### LINKED ISSUE #2943: UnsolvedSymbolException thrown on Stream.<func>(<some lambda>).
When parsing following code:
```java
package foo;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;
public class TestPeek {
    public void foo() {
        Stream.of(1,2,3).peek(info -> { System.out.println(info); }).collect(Collectors.toList());
    }
}
```

When trying to resolve the `MethodCallExpr`, I get the following exception:
```
Exception in thread "main" UnsolvedSymbolException{context='Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
}).collect(Collectors.toList())', name='Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
})', cause='java.lang.RuntimeException: Method 'peek' cannot be resolved in context Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
}) (line: 7) MethodCallExprContext{wrapped=Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
})}. Parameter types: [com.github.javaparser.resolution.types.ResolvedVoidType@179ece50]'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:171)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:321)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:183)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at com.sankuai.ia.parser.Test.lambda$null$0(Test.java:45)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.sankuai.ia.parser.Test.lambda$main$1(Test.java:42)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.ifClassOrInterfaceDeclaration(ClassOrInterfaceDeclaration.java:276)
	at com.sankuai.ia.parser.Test.main(Test.java:40)
Caused by: java.lang.RuntimeException: Method 'peek' cannot be resolved in context Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
}) (line: 7) MethodCallExprContext{wrapped=Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
})}. Parameter types: [com.github.javaparser.resolution.types.ResolvedVoidType@179ece50]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:748)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:320)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:97)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:551)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:398)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:414)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:380)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 10 more
```

For reproduction:
```java
package test;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.stmt.Statement;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class Test {
    public static void main(String[] args) {
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(
                "package foo;\n"
                        + "import java.util.stream.Collectors;\n"
                        + "import java.util.stream.IntStream;\n"
                        + "import java.util.stream.Stream;\n"
                        + "public class TestPeek {\n"
                        + "    public void foo() {\n"
                        + "        Stream.of(1,2,3).peek(info -> { System.out.println(info); }).collect(Collectors.toList());\n"
                        + "    }\n"
                        + "}"
        );

        for (TypeDeclaration<?> type : cu.getTypes()) {
            type.ifClassOrInterfaceDeclaration(classDecl -> {
                for (MethodDeclaration method : classDecl.getMethods()) {
                    method.getBody().ifPresent(body -> {
                        for (Statement stmt : body.getStatements()) {
                            for (MethodCallExpr methodCallExpr : stmt.findAll(MethodCallExpr.class)) {
                                ResolvedMethodDeclaration resolvedMethodCall = methodCallExpr.resolve();
                                String methodSig = resolvedMethodCall.getQualifiedSignature();
                                System.out.println(methodSig);
                            }
                        }
                    });
                }
            });
        }
    }
}

```

### PR DESCRIPTION
**Pull request by qzchenwl**
Fixes #2943.

### CODE REVIEW

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java [hunk 1]
```diff
@@ -187,7 +187,7 @@ void typeOfVoidLambda() {
 
         JavaParserFacade javaParserFacade = JavaParserFacade.get(new ReflectionTypeSolver());
         ResolvedType type = javaParserFacade.getType(lambdaExpr);
-        assertEquals("void", type.describe());
+        assertEquals("java.util.function.Consumer<? super java.lang.String>", type.describe());
```
Comment (qzchenwl) [inline javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java:190]: Lambda always has "function" type, never be `void`.

**Review by jlerbsc — APPROVED** [review]

**Review by jlerbsc — APPROVED** [review]

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java (hunk 1 above)
Comment (MysterAitch) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java:190]: I am confused about the sample used within this test:

```java
import java.util.List;
import java.util.stream.IntStream;

public class Agenda {

    private List<String> persons;

    public void lambdaEmpty() {
        return persons.stream().forEach(p -> {
            System.out.println(p);
        });
    }

}
```

Note that `.forEach()` is void return type, AND `lambdaEmpty` is void return type... So why is there a `return ...`?

Which means that the original test is "wrong" or otherwise needs amending..?

Comment (MysterAitch) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/LambdaResolutionTest.java:190]: I add the above as a comment -- it doesn't change this PR :+1: 

Note this equivalent code where the parameter to `stringConsumer` is extracted as a variable with an explicit type:

```java
    public void lambdaEmpty() {
        java.util.function.Consumer<String> stringConsumer = p -> {
            System.out.println(p);
        };
        persons.stream().forEach(stringConsumer);
    }
```
