### PR TITLE
Parse modules and their directives

### LINKED ISSUE #1558: Parsing a Jigsaw module statement does not work
Should `JavaParser.parseStatement("exports org.javacord.api.entity.channel.internal to org.javacord.core;");` not work?
Actually `ModuleStmt` does not implement `Statement`, so I guess no, but why?
If there is no reason, I'd suggest to add this, or how are you supposed to parse a single module statement?

### PR DESCRIPTION
**Pull request by matozoid**
Add parse methods and clear up some documentation.

Fixes #1558 

Any comments, @Vampire ?

### CODE REVIEW

**Comment by matozoid** [comment]
Also fixes #1559

File: javaparser-core-testing/src/test/java/com/github/javaparser/modules/ModuleDeclarationTest.java [hunk 1]
```diff
@@ -178,4 +181,24 @@ public void testCsmPrinting() {
...
+                .addDirective("uses org.javacord.api.util.internal.DelegateFactoryDelegate;");
+
+        assertEqualsNoEol("@Generated(generator) @SuppressWarnings(\"module\") \n" +
+                "module org.javacord.api {\n" +
+                "    requires transitive java.desktop;\n" +
+                "    exports org.javacord.api.entity.channel;\n" +
+                "    exports org.javacord.api.entity.channel.internal to org.javacord.core;\n" +
+                "    uses org.javacord.api.util.internal.DelegateFactoryDelegate;\n" +
+                "}\n", moduleDeclaration.toString());
+    }
```
Comment (Vampire) [inline javaparser-core-testing/src/test/java/com/github/javaparser/modules/ModuleDeclarationTest.java]: Would you mind replacing by dummy names?
I'm not sure, it being a good practice to contain other projects code in your tests.
And remove the `Generated`, unfortunately the compiler complains that Generated (neither the old, nor the new one) target modules.

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java [hunk 2]
```diff
@@ -197,4 +202,12 @@ public boolean replace(Node node, Node replacementNode) {
         }
         return super.replace(node, replacementNode);
     }
+
+    /**
+     * Add a directive to the module, like "
+     */
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java]: like what?

**Review by Vampire — CHANGES_REQUESTED** [review]
Maybe also add `ModuleExportsStmt ModuleExportsStmt#addModuleName(String)`, and `ModuleDeclaration#addDirective(ModuleStmt)` for
```java
moduleDirectives
    .addLast(new ModuleExportsStmt()
        .setName("foo.bar")
        .addModuleName("other.foo")
        .addModuleName("other.bar")
    )
```
and
```java
moduleDeclaration
    .addDirective(new ModuleExportsStmt()
        .setName("foo.bar")
        .addModuleName("other.foo")
        .addModuleName("other.bar")
    )
```

File: javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java [hunk 3]
```diff
@@ -226,24 +226,35 @@ public void everyTokenHasACategory() throws IOException {
...
         assertEquals("j", forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(1).getNameAsString());
-        assertEquals(false, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(0).getInitializer().isPresent());
-        assertEquals(true, forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(1).getInitializer().isPresent());
+        assertFalse(forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(0).getInitializer().isPresent());
+        assertTrue(forStmt.getInitialization().get(0).asVariableDeclarationExpr().getVariables().get(1).getInitializer().isPresent());
+    }
+
+    @Test
+    public void parseModuleDeclaration() {
+        JavaParser.getStaticConfiguration().setLanguageLevel(JAVA_9);
```
Comment (Vampire) [inline javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java]: Is it good to change the static configuration in a test?

File: javaparser-core-testing/src/test/java/com/github/javaparser/modules/ModuleDeclarationTest.java (hunk 1 above)
Comment (matozoid) [reply javaparser-core-testing/src/test/java/com/github/javaparser/modules/ModuleDeclarationTest.java]: Oh sure!

File: javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java (hunk 3 above)
Comment (matozoid) [reply javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java]: Hey, this review stuff really works :-)

**Comment by matozoid** [comment]
Okay, comments processed!

File: javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java [hunk 4]
```diff
@@ -32,29 +32,41 @@
...
 import static com.github.javaparser.utils.TestUtils.assertInstanceOf;
 import static com.github.javaparser.utils.Utils.EOL;
-import static org.junit.Assert.assertEquals;
-import static org.junit.Assert.assertTrue;
+import static org.junit.Assert.*;
 
 public class JavaParserTest {
 
+    @Before
+    public void setToLatestJava() {
```
Comment (Vampire) [inline javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java:55]: Actually I did the same in the pretty printer test in the PR you just merged. Can you please change it there too?
It thought there might be some way to create a custom JavaParser with custom configuration, so that you can have differently configured parsers (is there not?) and was too lazy to find out how as it was not instantly clear, so I thought I wait until you solve my comment here. :-D

Comment (Vampire) [reply javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java:55]: Also, if it is only needed for one of the tests in the class, it might be better to do it at start and end of the test method, not in `@Before` and `@After`, as that will do it for all methods in the test class.

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java [hunk 5]
```diff
@@ -161,4 +164,9 @@ public void ifModuleExportsStmt(Consumer<ModuleExportsStmt> action) {
     public Optional<ModuleExportsStmt> toModuleExportsStmt() {
         return Optional.of(this);
     }
+
+    public ModuleExportsStmt addModuleName(String name) {
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java:168]: Was he naughty that he doesn't get some docs? :-)

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java [hunk 6]
```diff
@@ -197,4 +202,16 @@ public boolean replace(Node node, Node replacementNode) {
...
     }
+
+    /**
+     * Add a directive to the module, like "exports R.S to T1.U1, T2.U2;"
+     */
+    public ModuleDeclaration addDirective(String directive) {
+        return addDirective(JavaParser.parseModuleDirective(directive));
+    }
+
+    public ModuleDeclaration addDirective(ModuleStmt directive) {
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java:213]: also naughty?

File: javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java (hunk 4 above)
Comment (matozoid) [reply javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java:55]: Oh, yes you can simply do new JavaParser() and get an instance (see http://javaparser.org/the-quick-and-the-full-api-of-javaparser/) but the static methods don't know about that instance :-/

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java (hunk 5 above)
Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java:168]: I can't think of a doc that would add anything, so I let it speak for itself :-)

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java (hunk 6 above)
Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java:213]: Indeed!

File: javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java (hunk 4 above)
Comment (matozoid) [reply javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java:55]: Looks like your PP tests are fine - am I missing something?

Comment (Vampire) [reply javaparser-core-testing/src/test/java/com/github/javaparser/JavaParserTest.java:55]: I also did the static configuration thing witout resetting.
Look at #1565 what I mean, I fixed it for my test.
I'd always perfer local configuration for tests instead of static configuration or the tests influence each other probably.

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java (hunk 5 above)
Comment (Vampire) [reply javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java:168]: Ok, but while we are at self-explaining, I personally don't find the `moduleName` name pretty self-explanatory per-se. What is the module name(s) of an export statement? I know it now as I just tried it in absence of any other possibility to set the `to` part, but it was more trial & error than a self-explanatory name. ;-)
That mandates for a rename though, not for added JavaDoc. :-D

File: javaparser-core-testing/src/test/java/com/github/javaparser/modules/ModuleDeclarationTest.java [hunk 7]
```diff
@@ -180,4 +181,39 @@ public void testCsmPrinting() {
...
+                );
+
+        moduleDeclaration
+                .addDirective(new ModuleExportsStmt()
+                        .setName("foo.bar.x")
+                        .addModuleName("other.foo")
+                        .addModuleName("other.bar")
+                );
+
+        assertEqualsNoEol("@SuppressWarnings(\"module\") \n" +
```
Comment (Vampire) [inline javaparser-core-testing/src/test/java/com/github/javaparser/modules/ModuleDeclarationTest.java]: With my annotation prettifying PR in, you need to remove the space before the newline.

**Review by Vampire — CHANGES_REQUESTED** [review]

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java (hunk 6 above)
Comment (Vampire) [reply javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleDeclaration.java:213]: Ok, just thought because its sibling got docs, but that is probably because it is a string that has to be properly formatted. :-)

File: javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java (hunk 5 above)
Comment (Vampire) [reply javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java:168]: Ok, just thought because `ModuleDeclaration#addDirective(String)'  got docs, but that is probably because it is a string that has to be properly formatted. :-)

Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/ast/modules/ModuleExportsStmt.java:168]: Yes, here the type gives it away.
