### PR TITLE
Finding the functional method doesn't always succeed

### LINKED ISSUE #2595: [Java Symbol Solver] Resolve type from functional interface
**QUESTION**: does `javaparser` support the resolution of types from functional interfaces? Or the `java.lang.UnsupportedOperationException` addresses the lack of this functionality (see description below for more information)?

---
**PROBLEM**:
I have the following code which I try to resolve (*be careful*, `javaparser` types are coincidental, I am parsing a project that utilizes the usage of `javaparser`):
```java
@Override
    public List<Metric<Integer>> compute(CompilationUnit compilationUnit) {
        Set<String> foreignProviders = new HashSet<>();
        ClassMetric<Integer> fdp = c -> {
            List<String> classFieldNames = getAllClassFieldNames(c);
            // DELETED FOR SAKE OF BREVITY
            return foreignProviders.size();
        };
        return getMetricForClass(fdp, compilationUnit);
    }
```
There seems to be a problem with resolution of `getAllClassFieldNames(c);`.  The parameter `c` is of type `ClassOrInterfaceDeclaration` (*be careful*, `javaparser` types are coincidental, I am parsing a project that utilizes the usage of `javaparser`) and it comes from the following functional interface:
```java
@FunctionalInterface
public interface ClassMetric<T> extends Function<ClassOrInterfaceDeclaration, T> {
    T apply(ClassOrInterfaceDeclaration c);
}
```

I get the following exception. There seems to be a problem with resolution of the type from the interface.

```
Exception in thread "main" java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: getAllClassFieldNames(c), Parameter: c
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:225)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:240)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:140)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Scratch.lambda$main$1(scratch_4.java:36)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at Scratch.main(scratch_4.java:36)
Caused by: java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.LambdaExprContext.solveSymbolAsValue(LambdaExprContext.java:127)
<CUT FOR SAKE OF BREVITY>
```
I added the required `TypeSolvers` (`JarTypeSovler` for `javaparser` library jar and `JavaParserTypeSolver` for the project itself) to my `JavaParser` configuration. I can post this code as well.

### PR DESCRIPTION
**Pull request by maartenc**
Finding the functional method doesn't always succeed when there is more than 1 abstract method in the class hierarchy.

Fixes #2595

### CODE REVIEW

File: javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/logic/AbstractTypeDeclaration.java [hunk 1]
```diff
@@ -43,23 +47,43 @@
...
-                    methods.add(mu);
+                    methods.add(ancestorMethodUsage);
                 }
             }
         }
 
         return methods;
     }
 
+    private String getSignature(MethodUsage mu) {
```
Comment (MysterAitch) [inline javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/logic/AbstractTypeDeclaration.java]: Is there a reason for using a custom private method here rather than using the `getMethodSignature()` method?

My presumption is the answer is "yes" and that there's something I'm currently not seeing :)

**Comment by MysterAitch** [comment]
Looks good, thank you @maartenc ! :) 

Other than the comment re: if that private method belongs in that class (e.g. could it be moved to `MethodUsage`?), happy to merge it in! 

That could probably be done as a separate PR if desired.

**Comment by maartenc** [comment]
Thanks for the feedback @MysterAitch : I'll look at it tomorrow :-)

File: javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/logic/AbstractTypeDeclaration.java (hunk 1 above)
Comment (maartenc) [reply javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/logic/AbstractTypeDeclaration.java]: I coulnd't find a `getMethodSignature()` method, did you mean why I didn't use the `methodDeclaration.getSignature()` method?

To find overridden generic methods, I need a signature where the generic types have been replaced with the information from the subclass.

For instance, consider the example:

```
public static interface Foo<S, T> extends Function<S, T> {

    T foo(S str);

    @Override
    default T apply(S str) {
        return foo(str);
    }
}
```

If we use the `methodDeclaration.getSignature()` method, we have the following signatures:
`apply(S)`, `foo(S)` (from `Foo`) and `apply(T)` (from `Function`)

But we don't want the `apply(T)` here since it's overridden by `apply(S)`.
For that, I've copied the logic from `methodDeclaration.getSignature()` into a private method and execute it on a `MethodUsage `object (and not on a `MethodDeclaration`).

That method could probably be added as a public method to `MethodUsage`, but I'm not sure it is usable at other places...

**Comment by maartenc** [comment]
I tried to explain it a little more @MysterAitch . I hope it makes sense what I'm saying...
If you think that private method should be a public method of MethodUsage instead, I can update the PR, no problem.

thanks,
Maarten

File: javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/logic/AbstractTypeDeclaration.java (hunk 1 above)
Comment (MysterAitch) [reply javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/logic/AbstractTypeDeclaration.java]: > I coulnd't find a `getMethodSignature()` method, did you mean why I didn't use the `methodDeclaration.getSignature()` method?

Apologies, yes you are correct! Typo on my part!

edit: I had in mind `methodUsage.getSignature()` (as opposed to `methodDeclaration.getSignature()`), but I see now that this method doesn`t yet exist.

**Comment by MysterAitch** [comment]
I've just re-read the comment and realised that I had in mind `methodUsage.getSignature()` (as opposed to `methodDeclaration.getSignature()`), but I see now that this method doesn`t yet exist.

After thinking this through, I think I have come to the conclusion that yes I would prefer to have `MethodUsage#getSignature` and `MethodUsage#getQualifiedSignature` available (see the code and debugger screenshot below). The benefit I see here is that the declared (generic) types are available via `methodUsage.getDeclaration().getSignature()`, and the concrete types are available via `methodUsage.getSignature()`. This isn't a strongly-held view (meaning that I'm happy to be talked out of this) :+1: 

If that's something you're happy to tweak this PR to make happen then go for it, otherwise I'll merge this as-is later this afternoon :) 



```java

    // replacement within MethodUsage.java (note pre-existing TODO re: making use the type parameters)
    public String getQualifiedSignature() {
        return getDeclaration().getQualifiedName() + "." + getSignature();
    }

    
    // added to MethodUsage.java
    public String getSignature() {
        StringBuilder sb = new StringBuilder();
        sb.append(getName());
        sb.append("(");
        for (int i = 0; i < getNoParams(); i++) {
            if (i != 0) {
                sb.append(", ");
            }
            sb.append(getParamType(i).describe());
        }
        sb.append(")");
        return sb.toString();
    }
```

image


Thank you again for the fix! :+1:

**Comment by maartenc** [comment]
Good suggestion @MysterAitch , I've updated this PR :-)

**Comment by MysterAitch** [comment]
Oops, looks like I gave you bad code, sorry! 

It's also visible in the screenshot too (`.apply.apply()`) but I missed that.

```
Expected: is "AnonymousClassDeclarations.DoFn.ProcessContext.innerClassMethod()" 

 but: was "AnonymousClassDeclarations.DoFn.ProcessContext.innerClassMethod.innerClassMethod()"
```

I've stepped away but maybe use the parent's qualified name? Not sure offhand what is available/visible.

**Comment by maartenc** [comment]
Ha no problem, I didn't see it either... :-)
I've committed a new attempt...

**Comment by maartenc** [comment]
Thanks @MysterAitch !
I think you can close PR #2604 as well...

Maarten
