### PR TITLE
Fix #4864: Correct toString() output in ReflectionRecordDeclaration

### LINKED ISSUE #4864: [BUG] Incorrect toString in ReflectionRecordDeclaration
[ReflectionRecordDeclaration.java](https://github.com/javaparser/javaparser/blob/b87bb5d80f2d0bdeae806aa17d6ce418ef8255bd/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionRecordDeclaration.java#L208) prints "ReflectionClassDeclaration" in `toString()` instead of "ReflectionRecordDeclaration", leading to confusing/misleading error messages.

### PR DESCRIPTION
**Pull request by ChenduanZhang**
### Fixes
Fixes #4864  

### Test
- Added a new test case `testToStringShouldUseCorrectClassName()` in `ReflectionRecordDeclarationTest`

### Details
- Use getClass().getSimpleName() to update toString() to print "ReflectionRecordDeclaration" instead of "ReflectionClassDeclaration"

### CODE REVIEW

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionRecordDeclarationTest.java [hunk 1]
```diff
@@ -396,4 +396,18 @@ void genericConstructorTest() {
...
     }
+
+    @Test
+    @EnabledForJreRange(min = org.junit.jupiter.api.condition.JRE.JAVA_17)
+    void testToStringShouldUseCorrectClassName() {
+        ReflectionRecordDeclaration decl =
+                (ReflectionRecordDeclaration) typeSolver.solveType("box.Box");
+
+        String result = decl.toString();
+        System.out.println("toString() output = " + result);
```
Comment (jlerbsc) [inline javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionRecordDeclarationTest.java]: This is not good practice.

**Comment by jlerbsc** [comment]
Please squash your commits for better readability.

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionRecordDeclarationTest.java (hunk 1 above)
Comment (ChenduanZhang) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionRecordDeclarationTest.java]: Thanks! I will remove the System.out.println() and keep only the assertion.

**Comment by ChenduanZhang** [comment]
> Please squash your commits for better readability.

Done — squashed commits into one for better readability.

**Comment by jlerbsc** [comment]
Why do you close and reopen the PR? This generates alerts, which are annoying.

**Comment by jlerbsc** [comment]
Could this change inspire other similar changes (for example, in the ReflectionClassDeclaration class)?
Please make a separate commit for the other improvements.

**Comment by ChenduanZhang** [comment]
Sorry, I accidentally closed the PR — that was unintentional.
I’m happy to look into your suggestion about similar changes.

**Comment by ChenduanZhang** [comment]
Done — updated all classes in reflectionmodel with the same toString() style and pushed a separate commit

**Comment by jlerbsc** [comment]
Have you squashed your commits?

**Comment by ChenduanZhang** [comment]
Yes, I’ve squashed the commits. All other similar updates have been into the new commit:
refactor(reflectionmodel): use getClass().getSimpleName() in toString() methods. 
Should I also squash the previous commit for ReflectionRecordDeclaration and the new commit for a cleaner history?

**Comment by jlerbsc** [comment]
Is the ticket finished for you?

**Comment by ChenduanZhang** [comment]
I just noticed that one of the checks failed, so I added a test for this issue. If all the tests pass this time, I’ll squash the commits and it’ll be finished.

**Comment by ChenduanZhang** [comment]
I’ve finished the updates and squashed the commits for a clean history.

**Comment by jlerbsc** [comment]
Thank you for this contribution.
