### PR TITLE
More alignment corrections

### LINKED ISSUE #1570: Indentation of code block in wrapped method call chains still wrong
The indentation of code blocks in method call chains is still wrong.
Now it is indented too far.
If you change `com.github.javaparser.printer.PrettyPrinterTest#prettyAlignMethodCallChainsIndentsArgumentsWithBlocksCorrectly` to

```java
        CompilationUnit cu = JavaParser.parse("class Foo { void bar() { foo().bar().baz(() -> { if (Object.class.isAssignableFrom(this)) { boo().baa().bee(); } boo().baa().bee(); }).bam(); } }");
```

and

```java
        assertEqualsNoEol("class Foo {\n" +
                "\n" +
                "    void bar() {\n" +
                "        foo().bar()\n" +
                "             .baz(() -> {\n" +
                "                 if (Object.class.isAssignableFrom(this)) {\n" +
                "                     boo().baa()\n" +
                "                          .bee();\n" +
                "                 }\n" +
                "                 boo().baa()\n" +
                "                      .bee();\n" +
                "             })\n" +
                "             .bam();\n" +
                "    }\n" +
                "}\n", printed);
```

You will see the failure :-(

### PR DESCRIPTION
**Pull request by matozoid**
Fixes #1570 
@Vampire ?

### CODE REVIEW

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java [hunk 1]
```diff
@@ -714,7 +714,11 @@ public void visit(final MethodCallExpr n, final Void arg) {
         printComment(n.getComment(), arg);
         n.getScope().ifPresent(scope -> {
             scope.accept(this, arg);
-            if (configuration.isColumnAlignFirstMethodChain()) {
+            // pick the kind of expressions where vertically aligning method calls is okay.
+            boolean mayAlignColumns = n.findParent(Statement.class)
+                    .map(p -> p.isReturnStmt() || p.isExpressionStmt())
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java]: How about `ThrowStmt` and `AssertStmt`?
Shouldn't those also apply?

This calculation is not really costly, is it?
Because if it is, it should be done inside the `if (configuration.isColumnAlignFirstMethodChain())` block instead of in front of it.

**Review by Vampire — CHANGES_REQUESTED** [review]
Nice, thanks :-)

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java (hunk 1 above)
Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java]: Oops, caught me cutting corners :-) I'll go through all statements tonight and see if they should be in the list.

Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java]: `AssertStmt` `LabeledStmt` `ReturnStmt` `ThrowStmt` I would guess.

Comment (Vampire) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java]: Doesn't a `LabeledStmt` always wrap another `Statement`, so will never be returned at this place? 

`AssertStmt` maybe too, yes.

Don't forget `ExpressionStmt`.
