### PR TITLE
Let SourceRoot skip unlikely directories

### LINKED ISSUE #1427: SourceRoot.tryToParse() doesn't ignore hidden directories
In my project some template java files in the `/.idea` are present that get picked up by the SourceRoot's FileVisitor. For some reason the relative path is changed from `/.idea/fileTemplates/code/Catch Statement Body.java` to `/idea/fileTemplates/code/Catch Statement Body.java`, which throws a `NoSuchFileException`.

```
java.nio.file.NoSuchFileException: /idea/fileTemplates/code/Catch Statement Body.java
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.github.javaparser.Providers.provider(Providers.java:70)
	at com.github.javaparser.Providers.provider(Providers.java:74)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:109)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:124)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:144)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:139)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:139)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:159)
```

A solution would be to skip hidden directories upon visiting the files, add this function
```
@Override
  public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
    if (Files.isHidden(dir) || roots.stream().anyMatch(dir::startsWith)) {
      return SKIP_SIBLINGS;
    }
    return CONTINUE;
}
```
to the FileVisitor

```
public List<ParseResult<CompilationUnit>> tryToParse(String startPackage) throws IOException {
    assertNotNull(startPackage);
    logPackage(startPackage);
    final Path path = packageAbsolutePath(root, startPackage);
    Files.walkFileTree(path, new SimpleFileVisitor<Path>() {
        @Override
        public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
            if (!attrs.isDirectory() && file.toString().endsWith(".java")) {
                Path relative = root.relativize(file.getParent());
                tryToParse(relative.toString(), file.getFileName().toString());
            }
            return FileVisitResult.CONTINUE;
        }
    });
    return getCache();
}
```

### PR DESCRIPTION
**Pull request by matozoid**
Fixes #1427

### CODE REVIEW

File: javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java [hunk 1]
```diff
@@ -143,12 +147,27 @@ public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IO
...
+
+            @Override
+            public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
+                return isSensibleDirectoryToEnter(dir)?CONTINUE:SKIP_SUBTREE;
             }
         });
         return getCache();
     }
 
+    private static boolean isSensibleDirectoryToEnter(Path dir) throws IOException {
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java:161]: Nice

File: javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java [hunk 2]
```diff
@@ -269,7 +288,12 @@ public FileVisitResult visitFile(Path absolutePath, BasicFileAttributes attrs) t
                         }
                     }
                 }
-                return FileVisitResult.CONTINUE;
+                return CONTINUE;
+            }
+
+            @Override
+            public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
+                return isSensibleDirectoryToEnter(dir)?CONTINUE:SKIP_SUBTREE;
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java]: I would add a few spaces around operators here

**Review by ftomassetti — APPROVED** [review]
+1
