### PR TITLE
Fixes #2625 Add messages to thrown exceptions

### LINKED ISSUE #2625: Add messages to thrown exceptions
We have quite a few calls to `new UnsupportedOperationException()` (and similar) without a message to describe why it is unsupported. 

In most cases this will be because an inherited method is not appropriate for that particular sub-class based on the rules/logic of Java / the AST.

In other cases this will be because it's not yet implemented or similar.

Adding in messages to these calls will make the distinction more visible / apparent to any users that come across this, and future developers who are looking at those bits of code.

### PR DESCRIPTION
**Pull request by oannhpham**
Fixes #2625 

I have added messages to `UnsupportedOperationException` that did not have messages and modified some which I thought were unclear. Please let me know if there are any message that are unclear.

### CODE REVIEW

File: javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalDifferenceCalculator.java [hunk 1]
```diff
@@ -325,7 +325,7 @@ private void calculatedSyntaxModelForNode(CsmElement csm, Node node, List<CsmEle
         } else if (csm instanceof CsmChild) {
             elements.add(csm);
         } else {
-            throw new UnsupportedOperationException(csm.getClass().getSimpleName() + " " + csm);
+            throw new UnsupportedOperationException("Unknown element type: " + csm.getClass().getSimpleName() + " " + csm);
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalDifferenceCalculator.java]: This is a concrete syntax model type

File: javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Added.java [hunk 2]
```diff
@@ -92,7 +92,7 @@ public TextElement toTextElement() {
             if (element instanceof CsmToken) {
             return new TokenTextElement(((CsmToken) element).getTokenType(), ((CsmToken) element).getContent());
         }
-        throw new UnsupportedOperationException(element.getClass().getSimpleName());
+        throw new UnsupportedOperationException("Unsupported element type: " + element.getClass().getSimpleName());
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Added.java:95]: This is a concrete syntax model type

File: javaparser-core/src/main/java/com/github/javaparser/printer/ConcreteSyntaxModel.java [hunk 3]
```diff
@@ -222,7 +222,7 @@ public static CsmElement forClass(Class<? extends Node> nodeClazz) {
             throw new IllegalStateException(s);
         });
         if (!concreteSyntaxModelByClass.containsKey(nodeClazz)) {
-            throw new UnsupportedOperationException(nodeClazz.getSimpleName());
+            throw new UnsupportedOperationException("Class " + nodeClazz.getSimpleName() + " not found!");
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/printer/ConcreteSyntaxModel.java:225]: This is a concrete syntax model class

File: javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/NodeText.java [hunk 4]
```diff
@@ -137,7 +137,7 @@ public void remove(TextElementMatcher matcher, boolean potentiallyFollowingWhite
                             elements.remove(i);
                         }
                     } else {
-                        throw new UnsupportedOperationException();
+                        throw new UnsupportedOperationException("There is no element to remove!");
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/NodeText.java:140]: This is a text element

**Comment by jlerbsc** [comment]
Thank you for this contribution.
