### PR TITLE
fix: issue 4358 prevent infinite cycles with static imports

### LINKED ISSUE #4358: StackOverflowError with import static in circular dependencies
Hi 👋 I encountered a `StackOverflowError` when trying to use javaparser on a popular open source library.

I managed to reproduce the issue in a minimal example.

> [!NOTE]
> I detected the problem javaparser `3.25.9`, but I was able to reproduce it on older versions.

The code I use for testing:

_Main.java_

``` java
package org.example;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import java.io.File;
import java.io.FileNotFoundException;

public class Main {
  public static void main(String[] args) throws FileNotFoundException {
    var rts = new ReflectionTypeSolver();
    var jpts = new JavaParserTypeSolver(new File("src/main/java"));
    var cts = new CombinedTypeSolver();
    cts.add(rts);
    cts.add(jpts);
    var pc = new ParserConfiguration()
        .setSymbolResolver(new JavaSymbolSolver(cts));
    StaticJavaParser.setConfiguration(pc);
    var cu = StaticJavaParser.parse(new File("src/main/java/org/example/A.java"));
    cu.findAll(MethodCallExpr.class).forEach(MethodCallExpr::resolve);
  }
}
```

_A.java_

``` java
package org.example;

import static org.example.B.d;

class A {
  void c() {
    d();
  }
}
```

_B.java_

``` java
package org.example;

class B extends A {
  static void d() {
  }
}
```

The issue doesn't happen when I use a fully qualified call (`B.d()`) and don't use `import static`.

Same thing happens with an asterisk import.

> [!NOTE]
> For the curious, the open source library where I discovered this problem is JUnit 5. Class `A` corresponds to [Filter](https://github.com/junit-team/junit5/blob/releases/5.9.x/junit-platform-engine/src/main/java/org/junit/platform/engine/Filter.java), class `B` to [CompositeFilter](https://github.com/junit-team/junit5/blob/releases/5.9.x/junit-platform-engine/src/main/java/org/junit/platform/engine/CompositeFilter.java), method `c` to `composeFilters` and method `d` to `alwaysIncluded`.

### PR DESCRIPTION
**Pull request by kdunee**
Fixes #4358 (infinite loop when `import static` is used between an ancestor and parent class).

### CODE REVIEW

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+    ReflectionTypeSolver rts = new ReflectionTypeSolver();
+    JavaParserTypeSolver jpts = new JavaParserTypeSolver(issueResourcesPath);
+    CombinedTypeSolver cts = new CombinedTypeSolver();
+    cts.add(rts);
+    cts.add(jpts);
+    ParserConfiguration pc = new ParserConfiguration()
+        .setSymbolResolver(new JavaSymbolSolver(cts));
+    StaticJavaParser.setConfiguration(pc);
+    CompilationUnit cu = StaticJavaParser.parse(issueResourcesPath.resolve("foo/A.java"));
+    cu.findAll(MethodCallExpr.class).forEach(MethodCallExpr::resolve);
```
Comment (jlerbsc) [inline javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: Can't we check the result because there's only one method call?

Comment (jlerbsc) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: I'll accept this solution because it doesn't break the existing tests.

Comment (kdunee) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: @jlerbsc  The result is irrelevant, the test verifies that `StackOverflowError` isn't thrown during `resolve`. I considered adding a comment explaining it or explicitly using [assertDoesNotThrow](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html#assertDoesNotThrow(org.junit.jupiter.api.function.Executable)) to make it more clear.

Comment (jlerbsc) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: Does this mean that the method is not correctly solved?

Comment (kdunee) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: It is correctly solved 😉. I could add the assertions to make it clear that:

- The method is correctly solved.
- `StackOverflowError` isn't thrown.

Should I do that?

Comment (jlerbsc) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: Checking that the method is correctly resolved is sufficient. If we want to find the context, we can refer to the issue.

Comment (kdunee) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: Sounds good to me.
Thanks for reviewing the change. I'll let you know when I implement the assertion, can't do it right now.

Comment (jlerbsc) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: As soon as it's done, I'll validate the PR. Thank you for your contribution.

Comment (kdunee) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4358Test.java]: @jlerbsc Done. I also rebased my change onto current master.
