### PR TITLE
Fix issue #4791

### LINKED ISSUE #4791: Strings and Boxed types should be compared using "equals()"
These methods seemed to assume that in order to detect an unchanged argument (and to skip property change notification), identity comparison is appropriate. But this [would only work in rare circumstances](https://stackoverflow.com/a/32926523/7641). See also [SonarQube rule 4973](https://rules.sonarsource.com/java/type/Bug/RSPEC-4973).

Created from the PR https://github.com/javaparser/javaparser/pull/4790

### PR DESCRIPTION
**Pull request by bannmann**
Fixes #4791.

### CODE REVIEW

File: javaparser-core/src/main/java/com/github/javaparser/ast/comments/Comment.java [hunk 1]
```diff
@@ -83,7 +83,7 @@ public String getContent() {
     @Generated("com.github.javaparser.generator.core.node.PropertyGenerator")
     public Comment setContent(final String content) {
         assertNotNull(content);
-        if (content == this.content) {
+        if (content.equals(this.content)) {
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/ast/comments/Comment.java:86]: Can you explain how these classes were modified?

Comment (bannmann) [reply javaparser-core/src/main/java/com/github/javaparser/ast/comments/Comment.java:86]: I modified `PropertyGenerator.generateSetter()` to generate this whenever the property type is `String`, the code change is included in this PR.

After testing the generation manually in the working copy of my local repo, I copied the `PropertyGenerator` change to a second, pristine clone and then ran `./run_core_metamodel_generator.sh && ./run_core_generators.sh` there.

Later I wrote the unit tests, copied those to the second checkout as well and re-ran the generator scripts.

Finally, I squashed all the changes from the second working copy and pushed the resulting commit.

Let me know if anything's missing, or if you prefer separate commits for any of the steps I took.

**Comment by jlerbsc** [comment]
Thank you for your contribution. Could you simply separate the commit of the changes you made manually from those generated by the shell.

**Comment by bannmann** [comment]
Sure! Done.

**Comment by jlerbsc** [comment]
Thank you for this contribution.
