### PR TITLE
Issue1749: implement hasDirectlyAnnotation for JavaParserEnumDeclaration

### LINKED ISSUE #1749: hasDirectlyAnnotation method throws UnsupportedOperationException
`JavaParserEnumDeclaration.hasDirectlyAnnotation` method throws `UnsupportedOperationException`. 
Please execute the following sample to reproduce the issue.

**Stacktrace :** 
````
java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserEnumDeclaration.hasDirectlyAnnotation(JavaParserEnumDeclaration.java:105)
````

**Sample snippet :** 
````
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import java.io.FileNotFoundException;

public class Main {

    public static void main(String[] args) throws FileNotFoundException {
        JavaParser.getStaticConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        CompilationUnit cu = JavaParser.parse(
                "public class Employee {"
                + "    public enum Weekend { SUNDAY, SATURDAY }"
                + "    private Weekend weekend;"
                + "}"
        );
        FieldDeclaration field = (FieldDeclaration) cu.getClassByName("Employee").get().getMembers().get(1);
        ResolvedReferenceTypeDeclaration dec = field.getElementType().resolve().asReferenceType().getTypeDeclaration();
        System.out.println(dec.hasDirectlyAnnotation("javax.persistence.Embeddable"));
    }
}
````

### PR DESCRIPTION
**Pull request by ftomassetti**
Fix #1749 by revising hasDirectlyAnnotation for JavaParserEnumDeclaration and similar classes

### CODE REVIEW

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue1485.java [hunk 1]
```diff
@@ -17,12 +17,12 @@
...
 
-public class Issue1485 {
+public class Issue1485 extends AbstractTest {
 
     @Test
     public void issue1485withoutSpecifyingJARs() throws IOException {
-        File dir = new File("src/test/resources/issue1485");
-        File file = new File("src/test/resources/issue1485/Complex.java");
+        File dir = adaptPath("src/test/resources/issue1485").toFile();
+        File file = adaptPath("src/test/resources/issue1485/Complex.java").toFile();
```
Comment (matozoid) [inline javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue1485.java]: Try slowly refactoring things from File to Path.

**Comment by matozoid** [comment]
`Helper` and `AbstractTest` are pretty lame names :-(

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue1485.java (hunk 1 above)
Comment (ftomassetti) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue1485.java]: Let's start with this particular case

**Comment by ftomassetti** [comment]
Renaming Helper and AbstractTest

**Comment by matozoid** [comment]
+1 and thanks as always :-)

**Comment by ftomassetti** [comment]
Thank you for the review!
