### PR TITLE
Include source file path in failed ParseResult when parsing via SourceRoot #4786

### LINKED ISSUE #4786: Failed ParseResult needs reference to the source file
JavaParser version: 3.26.2
JDK version: 21

Context: 

I obtained the ```ParseResults``` using ```SourceRoot.tryToParse()``` on a source root. For the unsuccessful parse, the ```ParseResult.getResult()``` is null, which is fair. However, I get only the list of ```Problem``` having error message and stack trace, but not the reference to the file that failed parsing. It would be helpful to include at least the FQN to the class name or the path to the source file. If it is possible keep reference to unparsed file as broken, it would be wonderful, so that I can get the contents as text continue the processing.

### PR DESCRIPTION
**Pull request by JIN-RUI-LIU**
Fixes #4786.
Problem: Failed parses from SourceRoot.tryToParse() don’t indicate which file failed (ParseResult has Problems but no file path).
Change: ParseResult now carries an internal sourcePath set by SourceRoot; on failures, ParseResult.toString() includes “for <absolute-path>”. Successful parses still set CompilationUnit storage as before.
Tests: Added issues/Issue4786Test to reproduce the “file content is only ‘\u’” failure and assert diagnostics include the absolute file path.
Compatibility: Backward compatible.

### CODE REVIEW

File: javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java [hunk 1]
```diff
@@ -445,7 +448,8 @@ public SourceRoot add(CompilationUnit compilationUnit) {
             final Path path = compilationUnit.getStorage().get().getPath();
             Log.trace("Adding new file %s", () -> path);
             final ParseResult<CompilationUnit> parseResult =
-                    new ParseResult<>(compilationUnit, new ArrayList<>(), null);
+                    new ParseResult<>(compilationUnit, new ArrayList<>(), null)
+                            .setSourcePath(path);
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java]: Why are you adding the source file path when there is no file parsing?

File: javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java [hunk 2]
```diff
@@ -430,7 +432,8 @@ public SourceRoot add(String startPackage, String filename, CompilationUnit comp
         assertNotNull(compilationUnit);
         Log.trace("Adding new file %s.%s", () -> startPackage, () -> filename);
         final Path path = fileInPackageRelativePath(startPackage, filename);
-        final ParseResult<CompilationUnit> parseResult = new ParseResult<>(compilationUnit, new ArrayList<>(), null);
+        final ParseResult<CompilationUnit> parseResult = new ParseResult<>(compilationUnit, new ArrayList<>(), null)
+                .setSourcePath(root.resolve(path));
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java]: Why are you adding the source file path when there is no file parsing?

File: javaparser-core/src/main/java/com/github/javaparser/ParseResult.java [hunk 3]
```diff
@@ -65,6 +79,19 @@ public void ifSuccessful(Consumer<T> consumer) {
...
 
+    /**
+     * Associates a source path with this parse result. Returns {@code this} for chaining.
+     * <p>
+     * Notes:
+     * - Intended for use by infrastructure (e.g., {@code SourceRoot}) to publish the originating file path.
+     * - Should be called immediately after parsing and not modified afterwards to avoid surprises in concurrent contexts.
+     * - The provided path is expected to be absolute.
+     */
+    public ParseResult<T> setSourcePath(Path sourcePath) {
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/ParseResult.java:88]: Curiously, there is no method for retrieving the path to the source file.

File: javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.util.List;
+import org.junit.jupiter.api.Test;
+
+/**
+ * Regression for issue 4786: when parsing via SourceRoot and a file fails to parse,
+ * diagnostics should indicate which file failed.
+ */
+public class Issue4786Test {
```
Comment (jlerbsc) [inline javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java]: These tests should be implemented in the SourceRootTest class.

File: javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+
+    @Test
+    void failedParse_shouldIncludeFilePath_whenFileContainsBackslashUOnly() throws IOException {
+        // Arrange: create a temporary source root and a file whose content triggers a scanner failure
+        Path tempDir = Files.createTempDirectory("jpv-issue4786");
```
Comment (jlerbsc) [inline javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java]: There is no need to create directories or new files because everything you need is in the ‘resources’ directory.

File: javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+        Path srcRoot = tempDir.resolve("src");
+        Files.createDirectories(srcRoot);
+
+        Path broken = srcRoot.resolve("OnlyUnicode.java");
+        // Write exactly two bytes: backslash and 'u'
+        Files.write(broken, new byte[] { (byte) '\\', (byte) 'u' });
```
Comment (jlerbsc) [inline javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java]: ??

File: javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+        // Act
+        List<ParseResult<CompilationUnit>> results = sourceRoot.tryToParse("");
+
+        // Assert
+        assertEquals(1, results.size(), "Expected one parse result");
+        ParseResult<CompilationUnit> result = results.get(0);
+        assertFalse(result.isSuccessful(), "Parsing should fail for this content");
+        assertFalse(result.getProblems().isEmpty(), "Problems should be present on failure");
+
+        String diag = result.toString();
```
Comment (jlerbsc) [inline javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java]: Useless

File: javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+        String expectedPath = broken.toAbsolutePath().toString();
+        assertTrue(diag.contains(expectedPath),
```
Comment (jlerbsc) [inline javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java]: The check must be based on a getSourcePath method that does not currently exist.

File: javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java [hunk 9]
```diff
@@ -432,8 +432,7 @@ public SourceRoot add(String startPackage, String filename, CompilationUnit comp
         assertNotNull(compilationUnit);
         Log.trace("Adding new file %s.%s", () -> startPackage, () -> filename);
         final Path path = fileInPackageRelativePath(startPackage, filename);
-        final ParseResult<CompilationUnit> parseResult = new ParseResult<>(compilationUnit, new ArrayList<>(), null)
-                .setSourcePath(root.resolve(path));
+        final ParseResult<CompilationUnit> parseResult = new ParseResult<>(compilationUnit, new ArrayList<>(), null);
```
Comment (jlerbsc) [inline javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java:427]: Creating a new commit to undo a previous commit is not the best solution for keeping a clean history. It makes your work unreadable. It would have been simpler to use Git's ‘Interactive Rebase’ feature.

**Comment by jlerbsc** [comment]
I am waiting for you to make the other changes before committing your work.

File: javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java (hunk 9 above)
Comment (JIN-RUI-LIU) [reply javaparser-core/src/main/java/com/github/javaparser/utils/SourceRoot.java:427]: OK，I‘ll try to figure it out

File: javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java (hunk 6 above)
Comment (JIN-RUI-LIU) [reply javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue4786Test.java]: In my first attempt I added a test resource whose content was a single backslash-u ("\u"). The goal was to deterministically trigger a scanner failure so that ParseResult would be unsuccessful and result() would be empty (as issue #4786 ). This let me verify that getSourcePath is present on failed parses.
Based on your feedback, I removed the custom “\u” fixture and now use an existing Java file under the utils test resources to trigger the failure. I also moved the test into SourceRootTest as requested and simplified the assertions to only check ParseResult.getSourcePath() (no dependency on toString).

**Comment by JIN-RUI-LIU** [comment]
> I am waiting for you to make the other changes before committing your work.

Thank you very much for your guidance!
I’ve updated all the changes you suggested.
Could you please let me know if there’s anything else that needs improvement?

**Comment by jlerbsc** [comment]
Can you squash your commits to make it more readable? Thank you.

**Comment by JIN-RUI-LIU** [comment]
> Can you squash your commits to make it more readable? Thank you.

Thanks for the reminder! I’ve already squashed all the commits into one commit.

**Comment by jlerbsc** [comment]
Now what happens if parsing fails? The issue mainly concerned cases where parsing failed, because in the other case the path is already available via cu.getStorage().getPath().

**Comment by JIN-RUI-LIU** [comment]
> Now what happens if parsing fails? The issue mainly concerned cases where parsing failed, because in the other case the path is already available via cu.getStorage().getPath().

In my first attempt I added a test resource whose content was a single backslash-u ("\u"). The goal was to deterministically trigger a scanner failure so that ParseResult would be unsuccessful and result() would be empty (as issue https://github.com/javaparser/javaparser/issues/4786 ). This let me verify that getSourcePath is present on failed parses.
The figure below shows the case when parsing fails. We can see that the path
image

Based on your feedback, I removed the custom “\u” fixture and now use an existing Java file under the utils test resources to trigger the failure.

**Comment by JIN-RUI-LIU** [comment]
I added sourcePathToStringTest to cover ParseResult.toString() with and without sourcePath, improving branch coverage and guarding against regressions. And I ran Spotless locally.
image
image

**Comment by jlerbsc** [comment]
On second thought, I wonder if it wouldn't be better to set the source path in the JavaParser class at the point where methods take a file or path as a parameter.

**Comment by JIN-RUI-LIU** [comment]
> On second thought, I wonder if it wouldn't be better to set the source path in the JavaParser class at the point where methods take a file or path as a parameter.

Thanks for the suggestion. To confirm: 
Do you mean that we should still generate a result even if parsing fails? (In this case, the result is null, and I would create a new one.) I'm not sure if that could have any side effects. If that’s what you intend, please let me know — I’ll create a new branch to handle it.

image

**Comment by JIN-RUI-LIU** [comment]
> On second thought, I wonder if it wouldn't be better to set the source path in the JavaParser class at the point where methods take a file or path as a parameter.

I thought about it again — or do you mean setting the sourcePath here, so that only the files that failed to parse would have their sourcePath set? Please let me know if that’s what you mean, and I’ll give it a try.
image

**Comment by jlerbsc** [comment]
> > On second thought, I wonder if it wouldn't be better to set the source path in the JavaParser class at the point where methods take a file or path as a parameter.
> 
> Thanks for the suggestion. To confirm: Do you mean that we should still generate a result even if parsing fails? (In this case, the result is null, and I would create a new one.) I'm not sure if that could have any side effects. If that’s what you intend, please let me know — I’ll create a new branch to handle it.
> 
> image

In practice, ParseResult is instantiated even in the event of a parsing error.

**Comment by jlerbsc** [comment]
> > On second thought, I wonder if it wouldn't be better to set the source path in the JavaParser class at the point where methods take a file or path as a parameter.
> 
> I thought about it again — or do you mean setting the sourcePath here, so that only the files that failed to parse would have their sourcePath set? Please let me know if that’s what you mean, and I’ll give it a try. image

If the parsing runs correctly, the compilation unit already knows the path of the parsed file (storage). However, in the event of an error, there is no information because the compilation unit is not instantiated. So in this case, the path should be stored in the ParseResult that is returned.
Furthermore, JavaParser declares parsing methods for which the provider is instantiated. It is therefore preferable to use these methods in the SourceRoot class.

**Comment by JIN-RUI-LIU** [comment]
> > > On second thought, I wonder if it wouldn't be better to set the source path in the JavaParser class at the point where methods take a file or path as a parameter.
> > 
> > 
> > I thought about it again — or do you mean setting the sourcePath here, so that only the files that failed to parse would have their sourcePath set? Please let me know if that’s what you mean, and I’ll give it a try. image
> 
> If the parsing runs correctly, the compilation unit already knows the path of the parsed file (storage). However, in the event of an error, there is no information because the compilation unit is not instantiated. So in this case, the path should be stored in the ParseResult that is returned. Furthermore, JavaParser declares parsing methods for which the provider is instantiated. It is therefore preferable to use these methods in the SourceRoot class.

Thank you for your guidance; I’ll give it a try.

**Comment by jlerbsc** [comment]
Why did you close this PR? Just make sure to squash your commits and isolate improvements to other classes in a specific commit.

**Comment by JIN-RUI-LIU** [comment]
> On second thought, I wonder if it wouldn't be better to set the source path in the JavaParser class at the point where methods take a file or path as a parameter.

Sorry to bother you again, but I’m a bit confused about this.
You suggested setting the source path in JavaParser.
However, SourceRoot.tryToParse() internally uses the Provider entry point:
image
in JavaParser.
Since the Provider doesn’t expose the file path, it seems there’s no way to retrieve it inside JavaParser.parse().
Please correct me if I’m missing something — thank you!

**Comment by JIN-RUI-LIU** [comment]
Here is my attempt to move setSourcePath into JavaParser. Since SourceRoot.tryToParse() calls the overload that also instantiates the provider, we cannot retrieve the path at the JavaParser layer. That means we would need to switch the parse() overload used inside SourceRoot.tryToParse(), but this does not seem reliable.

Here is SourceRoot.tryToParse() . I’m a bit worried that replacing the .parse() call with another method might cause some unintended side effects.


image


Here is what I changed to setSourcePath in JavaParser, but this method is Deprecated.


image
image

**Comment by jlerbsc** [comment]
The method that defines character encoding is deprecated because the input character encoding must be a configuration option so you can use the method that does not define the encoding.

**Comment by jlerbsc** [comment]
Thank you for your contribution.

**Comment by JIN-RUI-LIU** [comment]
> Thank you for your contribution.

Thank you for your guidance. I’ve learned a lot from this task.
