### PR TITLE
Fix issue 2374 Comments of added Nodes are ignored in LexicalPreservi…

### LINKED ISSUE #2374: Comments of added Nodes are ignored in LexicalPreservingPrinter
Given this example code
```java
public class Bar {
    public void foo() {
        System.out.print("Hello");
    }
}
```
If I parse it with javaparser and setup the AST with the LPP and adding a new node as
```java
Statement stmt = StaticJavaParser.parseStatement("System.out.println(\"World!\");");
stmt.setLineComment("Example comment");
```
the result of `LexicalPreservingPrinter#print` will look like this:
```java
public class Bar {
    public void foo() {
System.out.print("Hello!");
System.out.println("World!");
    }
}
```
I have taken a look into the code and found out, that the CSM does not fully support comments as `CsmComment`. Is there any plan to support these comments or is it even a bug? I found a work around for it by adding the new node to the AST first and afterwards adding the comment to the added node. Thank you!

### PR DESCRIPTION
**Pull request by jlerbsc**
Fixes #2374. I'm not sure that's the way to go

### CODE REVIEW

File: javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinter.java [hunk 1]
```diff
@@ -521,7 +522,10 @@ private static NodeText interpret(Node node, CsmElement csm, NodeText nodeText)
 
             pendingIndentation = false;
             if (element instanceof LexicalDifferenceCalculator.CsmChild) {
-                nodeText.addChild(((LexicalDifferenceCalculator.CsmChild) element).getChild());
+                Node child = ((LexicalDifferenceCalculator.CsmChild) element).getChild();
+                if (child.getComment().isPresent())
+                    nodeText.addToken(getTokenKind(child.getComment().get()), child.getComment().get().toString());
```
Comment (matozoid) [inline javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinter.java]: Optionals are intended to be used with functional style. `ifPresent` would work better here.

**Comment by matozoid** [comment]
Can you add a little test to demonstrate that it works?

File: javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java [hunk 2]
```diff
@@ -318,4 +319,17 @@ public ResolvedMethodDeclaration resolve() {
     public Optional<MethodCallExpr> toMethodCallExpr() {
         return Optional.of(this);
     }
+    
+    @Override
+    /**
+     * Returns the comment or an Optional.empty if there is no comment on this method call.
+     * In case of MethodCallExpr, Comment are setted in an the parent ExpressionStmt comment attribute. 
+     */
+    public Optional<Comment> getComment() {
```
Comment (matozoid) [inline javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java]: This is not logical: a comment is always set on the node where you want it. This problem should not be solved by making a single node behave inconsistently.

Comment (jlerbsc) [reply javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java]: Ok it's probably caused by 

    Statement stmt = StaticJavaParser.parseStatement("System.out.println(\"World!\");");
    stmt.setLineComment(lineComment);

Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java]: Ah, you mean that for something like a `MethodCallExpr`, which can end up in a `ExpressionStmt`, we have to consider two nodes when deciding whether it has a comment? So we might need to be able to query whether a node is a "pseudonode" which doesn't have any source code text of its own? I think the lex.pres.printer has some "ghost node" logic (or so) for that. But @ftomassetti can explain if he has some time :-)

Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java]: @jlerbsc - I still don't really get what you want to happen, but I guess this PR can be merged.

Comment (jlerbsc) [reply javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java]: @Matozoid, i'm completely wrong and this PR should not be merged. In the issue declared by @Implex1v, he add a comment to a statement (not a MethodCallExpr) so i don't really fix the issue.

Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/ast/expr/MethodCallExpr.java]: Well, it's merged already and it did fix something, I think? Otherwise I (or you) will make a revert PR.
