### PR TITLE
prettyAlignMethodCallChainsIndentsArgumentsWithBlocksCorrectly

### LINKED ISSUE #1543: Wrong indent in code blocks within broken down method call chains
The following Groovy code

```groovy
@Grab('com.github.javaparser:javaparser-symbol-solver-core:3.6.4')
import com.github.javaparser.JavaParser
import com.github.javaparser.printer.PrettyPrinter
import com.github.javaparser.printer.PrettyPrinterConfiguration

println new PrettyPrinter(new PrettyPrinterConfiguration().setColumnAlignFirstMethodChain(true)).print(JavaParser.parse('class Foo { void bar() { foo().bar().baz(() -> { boo().baa().bee(); }).bam(); } }'))
```

produces

```java
class Foo {

    void bar() {
        foo().bar()
             .baz(() -> {
            boo().baa()
                 .bee();
        })
             .bam();
    }
}
```

but I'd expect it to produce

```java
class Foo {

    void bar() {
        foo().bar()
             .baz(() -> {
                 boo().baa()
                      .bee();
             })
             .bam();
    }
}
```

So block indent = method call chain indent + configuration.indent instead of current indent + configuration.indent.
Basically the indent of the line where the block started + the configured indent.

### PR DESCRIPTION
**Pull request by matozoid**
Fixes #1543 

@Vampire can you review this?

### CODE REVIEW

**Comment by Vampire** [comment]
The actual code, or do you mean trying it out and verifying the result?

**Comment by matozoid** [comment]
The code. Or don't if you think I always produce perfect code :-)

**Comment by Vampire** [comment]
Surely not, noone does :-D
I'm just not sure I'm suitable for that as a foreigner to the codebase, but I can surely have a look later.

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java [hunk 1]
```diff
@@ -1460,13 +1446,9 @@ public void visit(NodeList n, Void arg) {
...
             NodeList<ImportDeclaration> modifiableList = new NodeList<>(n);
-            modifiableList.sort((left, right) -> {
-                int sort = Integer.compare(left.isStatic() ? 0 : 1, right.isStatic() ? 0 : 1);
-                if (sort == 0) {
-                    sort = left.getNameAsString().compareTo(right.getNameAsString());
-                }
-                return sort;
-            });
+            modifiableList.sort(
+                    comparingInt((ImportDeclaration left) -> left.isStatic() ? 0 : 1)
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrintVisitor.java]: shouldn't be called `left` anymore

File: javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java [hunk 2]
```diff
@@ -24,51 +24,65 @@
...
-            cursor = Position.pos(cursor.line, cursor.column + indentationLength);
-        }
+        append(indents.peek());
     }
 
     /**
      * Append the source string passed as argument to the buffer.
-     * If this is being appended at the beginning of a line, performs indentation first.
-     * <p> 
+     * If this is being appended at the beginning of a line, performs indentSize first.
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java]: Too many replacements I'd say

File: javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java [hunk 3]
```diff
@@ -82,12 +96,12 @@ public SourcePrinter print(final String arg) {
 
     /**
      * Append the source string passed as argument to the buffer, then append a newline.
-     * If this is being appended at the beginning of a line, performs indentation first.
-     * <p>  
+     * If this is being appended at the beginning of a line, performs indentSize first.
+     * <p>
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java]: Here also too many replacements I'd say

File: javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java [hunk 4]
```diff
@@ -24,51 +24,65 @@
...
         return this;
     }
 
     public SourcePrinter unindent() {
-        level--;
+        indents.pop();
         return this;
     }
 
+    private void append(String arg) {
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java]: Should also be used in `print()` and `println()`

**Review by Vampire — CHANGES_REQUESTED** [review]
lgtm besides the cosmetics I commented
And of course that this is a breaking change, but I guess this is ok for you?
I don't know your policy on this.

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java [hunk 5]
```diff
@@ -37,19 +37,23 @@
...
+        return indentString.toString();
     }
 
     /**
-     * Set the string to use for indenting. For example: "\t", "    ", "".
+     * Set the size of the indent in spaces.
      */
-    public PrettyPrinterConfiguration setIndent(String indent) {
+    public PrettyPrinterConfiguration setIndent(int indent) {
         this.indent = assertNotNull(indent);
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: Additionally, `assertNotNull` is not necessary anymore it just uselessly tests that the auto-boxing works

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java [hunk 6]
```diff
@@ -37,19 +37,23 @@
...
+    private int indent = 4;
     private String endOfLineCharacter = EOL;
     private Function<PrettyPrinterConfiguration, PrettyPrintVisitor> visitorFactory = PrettyPrintVisitor::new;
     private int maxEnumConstantsToAlignHorizontally = DEFAULT_MAX_ENUM_CONSTANTS_TO_ALIGN_HORIZONTALLY;
 
     public String getIndent() {
-        return indent;
+        StringBuilder indentString = new StringBuilder();
+        for(int i=0; i<indent; i++){
+            indentString.append(" ");
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: `'  '` should be enough, no need for a `String` object

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java (hunk 5 above)
Comment (Vampire) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: Or rather it should `assertNotNegative`

**Review by Vampire — CHANGES_REQUESTED** [review]
~~And there is probably a logic error if you combine method and call-chain aligning.
With `class Foo { void bar() { foo().bar().baz(() -> { boo().baa().bee(a, b, c); }).bam(); } }` and both options enabled you get~~
```java
...
```
~~instead of the expected~~
```java
...
```
Scratch that, wrong expectation.

File: javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java (hunk 4 above)
Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java]: Yes, except println because that does funny cursor logic.

**Comment by matozoid** [comment]
I wanted to write something about API breaking for a while, so here: http://javaparser.org/pragmatic-versioning/ :-)

File: javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java (hunk 4 above)
Comment (Vampire) [reply javaparser-core/src/main/java/com/github/javaparser/printer/SourcePrinter.java]: Ah, right, didn't look closely enough, then only for `print`

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java [hunk 7]
```diff
@@ -31,26 +33,49 @@
...
     private Function<PrettyPrinterConfiguration, PrettyPrintVisitor> visitorFactory = PrettyPrintVisitor::new;
     private int maxEnumConstantsToAlignHorizontally = DEFAULT_MAX_ENUM_CONSTANTS_TO_ALIGN_HORIZONTALLY;
 
+    /**
+     * Set the string to use for indenting. For example: "\t", "    ", "".
+     * @deprecated use setIndentSize
+     */
+    @Deprecated
+    public PrettyPrinterConfiguration setIndent(String indent) {
+        throw new NotImplementedException();
```
Comment (Vampire) [inline javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: How about instead the following?
- warn about deprecation if you do deprecation warnings
- if argument is spaces only, set `indentSize` to the length
- if argument contains anything else, throw exception (probably most users have couple of spaces or tabs, latter will maybe be added by my pending PR if you accept it, everything else is probably OK if it is not supported anymore)

Would make exisiting code simply continue to work like before besides a deprecation warning.

**Review by Vampire — CHANGES_REQUESTED** [review]

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java (hunk 7 above)
Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: Well, because we have little manpower and 194 issues open :-)

Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: Anyway, I assumed you were going to build a PR to make this stuff work again - but maybe I misunderstood. (Could be, happens more than I would like)

Comment (Vampire) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: I'll get tabs working properly with my PR, yes, as soon as you merged this, I'll probably adapt to the latest changes and submit it for your review. :-)

**Review by Vampire — APPROVED** [review]
lgtm 👍

File: javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java (hunk 7 above)
Comment (matozoid) [reply javaparser-core/src/main/java/com/github/javaparser/printer/PrettyPrinterConfiguration.java]: Here we go!
