### PR TITLE
Fix issue 4846

### LINKED ISSUE #4846: JavaParserTypeAdapter throw doesn't account for record declarations
`JavaParserTypeAdapter.solveType` contains code to wrap TypeDeclarations in their equivalent JavaParser type, but is missing a check for records, causing it to throw UnsupportedOperationException when it encounters one.

### PR DESCRIPTION
**Pull request by PiTheGuy**
Fixes #4846.

### CODE REVIEW

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4846Test.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+public class Issue4846Test extends AbstractResolutionTest {
+    public static final Path SRC_DIR = adaptPath("src/test/resources/issue4846");
+
+    private JavaParser javaParser;
+
+    @BeforeEach
+    void setup() {
+        // clear internal caches
+        JavaParserFacade.clearInstances();
```
Comment (jlerbsc) [inline javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4846Test.java]: This is not necessary in your test.

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4846Test.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+        javaParser = new JavaParser(configuration);
+    }
+
+    @Test
+    void test() throws IOException {
+        CompilationUnit cu = javaParser.parse(SRC_DIR.resolve("foo").resolve("Main.java")).getResult().get();
+        TypeDeclaration<?> typeDec = cu.getType(0);
+        MethodDeclaration methodDec = typeDec.getMethodsByName("foo").get(0);
+        methodDec.toDescriptor();
```
Comment (jlerbsc) [inline javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue4846Test.java]: There is no verification.

**Comment by jlerbsc** [comment]
You still need to use spotless to format your changes (mvn sptoless:apply).

**Comment by jlerbsc** [comment]
Thank you for your contribution.
