### PR TITLE
Fix #84

### LINKED ISSUE #84: com.github.javaparser.ast.body.Parameter.getType() can be null since 2.0.0
I assume a parameter's type being `null` only occurs for lambda expressions, thus why it didn't pop up until now.

This causes `NullPointerException`s at least for
- `com.github.javaparser.ast.visitor.GenericVisitorAdapter`
- `com.github.javaparser.ast.visitor.ModifierVisitorAdapter`
- `com.github.javaparser.ast.visitor.VoidVisitorAdapter`

The other adapters seem to be unaffected, one of them was explicitly adapted to it. I'd appreciate a double-check of this.

Before introducing a mere `if (parameter.getType() != null)` everywhere, I wanted to discuss how this should be approached. Does it make sense to introduce a new class representing lambda parameters? Although lambda parameters can have a type too, it seems that it's the only instance a paramater can have no type. Or am I missing something?

### PR DESCRIPTION
**Pull request by ptitjes**
I'm willing to put the correct thingies in the JBehave test suite if someone tells me where to act.

### CODE REVIEW

**Comment by ptitjes** [comment]
Ok that should do it!

File: javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+ */
+package com.github.javaparser.ast.type;
+
+import com.github.javaparser.ast.visitor.GenericVisitor;
+import com.github.javaparser.ast.visitor.VoidVisitor;
+
+/**
+ * @author Didier Villevalois
+ */
+public final class UnknownType extends Type {
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java:33]: I think a comment could be useful: it is not straightforward to understand what class represent

File: javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+ * JavaParser is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU Lesser General Public License for more details.
+ *
+ * You should have received a copy of the GNU Lesser General Public License
+ * along with JavaParser.  If not, see <http://www.gnu.org/licenses/>.
+ */
+/*
+ * Created on 05/10/2006
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java]: You have been working a lot on this class :D

File: javaparser-core/src/main/java/com/github/javaparser/ast/visitor/CloneVisitor.java [hunk 3]
```diff
@@ -429,6 +429,15 @@ public Node visit(WildcardType _n, Object _arg) {
 		return r;
 	}
 
+    @Override
+    public Node visit(UnknownType _n, Object _arg) {
+        Comment comment = cloneNodes(_n.getComment(), _arg);
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/ast/visitor/CloneVisitor.java]: Can an UnknownType have a comment?

Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/ast/visitor/CloneVisitor.java]: If so it should dumped in the DumpVisitor, if not is should be prevent to have a comment associated

File: javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericVisitor.java [hunk 4]
```diff
@@ -137,6 +133,8 @@
 
 	public R visit(WildcardType n, A arg);
 
+    public R visit(UnknownType n, A arg);
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericVisitor.java]: should we use the tabs until we reformat the whole class?

File: javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericVisitorAdapter.java [hunk 5]
```diff
@@ -1488,6 +1483,11 @@ public R visit(final UnaryExpr n, final A arg) {
 		return null;
 	}
 
+    @Override
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericVisitorAdapter.java]: as above, should we use tabs so that it is aligned to the other methods?

File: javaparser-testing/src/test/resources/com/github/javaparser/bdd/parsing_scenarios.story [hunk 6]
```diff
@@ -200,6 +200,23 @@ Then lambda in statement 3 in method 1 in class 1 is parent of contained paramet
...
+Given a CompilationUnit
+When the following source is parsed:
+package com.github.javapasrser.bdd.parsing;
+import java.util.function.Function;
+public class MultiParameterizedLambdas {
+    public static void main(String[] args) {
+        BiFunction<Integer, Integer, String> f = (a, b) -> String.valueOf(a) + String.valueOf(b);
+    }
+}
+Then lambda in statement 1 in method 1 in class 1 has parameters with non-null type
```
Comment (ftomassetti) [inline javaparser-testing/src/test/resources/com/github/javaparser/bdd/parsing_scenarios.story:219]: Should we also check that the type is the UnknownType?

File: javaparser-core/src/main/java/com/github/javaparser/ast/visitor/CloneVisitor.java (hunk 3 above)
Comment (ptitjes) [inline javaparser-core/src/main/java/com/github/javaparser/ast/visitor/CloneVisitor.java]: I think not. This is a kind of null object and can't receive any comment as it has no lexical representation.

File: javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericVisitor.java (hunk 4 above)
Comment (ptitjes) [inline javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericVisitor.java]: I'll put tabs. (The problem is that is it is different from files to files)

File: javaparser-testing/src/test/resources/com/github/javaparser/bdd/parsing_scenarios.story (hunk 6 above)
Comment (ptitjes) [inline javaparser-testing/src/test/resources/com/github/javaparser/bdd/parsing_scenarios.story:219]: Well the problem was that the type was null. So I guess checking for more is over-testing.

File: javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java (hunk 1 above)
Comment (ptitjes) [inline javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java:33]: Adding that.

File: javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java (hunk 2 above)
Comment (ptitjes) [inline javaparser-core/src/main/java/com/github/javaparser/ast/type/UnknownType.java]: Wow! Indeed I don't know where my IDE got that date...

**Comment by ptitjes** [comment]
Fixed!

**Comment by ftomassetti** [comment]
+1, thanks!
