### PR TITLE
Fixes issue 2099

### LINKED ISSUE #2099: Comment shift to new statement when adding statement
Hi, I'm trying to add a statement using addStatement on a BlockStmt (the method 'test' below) and the line comment seems to shift from one statement to the new (from the query.getLong(0); to the if statement), is this a bug in JavaParser? If it is, how can I work around that?

```
public class Teste {
    public void test(Uri uri, ContentProvider provider) {
        Cursor query = provider.query(uri, null, null, null, null);
        query.getLong(0); // Teste
    }
}
```

```
public class Teste {
    public void test(Uri uri, ContentProvider provider) {
            Cursor query = provider.query(uri, null, null, null, null);
            query.getLong(0); if(query != null) {
            query.close();
        }
        // Teste
    }
}
```

Thanks in advance

### PR DESCRIPTION
**Pull request by moraispgsi**
This pull request fixes #2099. Basically it adds a condition in the applyAddedDiffElement method to account for the commentary in the same line.

### CODE REVIEW

**Comment by matozoid** [comment]
Cool! Let's see what @ftomassetti says.

File: javaparser-core-testing/src/test/java/com/github/javaparser/ast/stmt/BlockStmtTest.java [hunk 1]
```diff
@@ -1,10 +1,18 @@
 package com.github.javaparser.ast.stmt;
 
+import com.github.javaparser.JavaParser;
```
Comment (moraispgsi) [inline javaparser-core-testing/src/test/java/com/github/javaparser/ast/stmt/BlockStmtTest.java]: The changes in this file are not necessary.

File: javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/TransformationsTest.java [hunk 2]
```diff
@@ -140,4 +145,54 @@ void exampleParam5() throws IOException {
         md.getBody().get().getStatements().add(new ReturnStmt(new NameExpr("p1")));
         assertTransformed("Example_param5", cu);
     }
+
+    @Test
+    void issue2099AddingAddingStatementAfterTraillingComment1() {
```
Comment (moraispgsi) [inline javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/TransformationsTest.java]: issue2099AddingAddingStatementAfterTraillingComment1 -> issue2099AddingStatementAfterTraillingComment1

File: javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/TransformationsTest.java [hunk 3]
```diff
@@ -140,4 +145,54 @@ void exampleParam5() throws IOException {
...
+                "    value2(); // Test\n" +
+                "    if(value != null) {\n" +
+                "        value.value();\n" +
+                "    }\n" +
+                "}";
+        assertEqualsNoEol(expected, s);
+    }
+
+    @Test
+    void issue2099AddingAddingStatementAfterTraillingComment2() {
```
Comment (moraispgsi) [inline javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/TransformationsTest.java]: issue2099AddingAddingStatementAfterTraillingComment2 -> issue2099AddingStatementAfterTraillingComment2

File: javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Difference.java [hunk 4]
```diff
@@ -572,6 +572,17 @@ private void applyAddedDiffElement(Added added) {
         }
 
         if (!used) {
+            if(nodeText.numberOfElements() > originalIndex + 1 &&
+                nodeText.getTextElement(originalIndex).isComment()) {
+                String expanded = nodeText.getTextElement(originalIndex).expand();
+                if(expanded.startsWith("/*")) {
```
Comment (ftomassetti) [inline javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Difference.java:593]: mmm. I would use an helper function, maybe putting it directly on the nodetext, to check if the node text is a comment. We should also consider line comments

**Review by ftomassetti — APPROVED** [review]
To me it works but I would refactor a little bit the change in Difference for clarity

File: javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Difference.java (hunk 4 above)
Comment (moraispgsi) [reply javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Difference.java:593]: It is considering line comments. You can see that both tests pass.

**Comment by matozoid** [comment]
@moraispgsi @ftomassetti - shall we merge and release this, or do I need to wait for refactoring?

**Comment by moraispgsi** [comment]
I have detected other problems concerning indentation and adding statements to a blockstmt that I will be submitting corrections for in the immediate future. As for the refactoring, I'm not sure what you would like me to do.

**Comment by ftomassetti** [comment]
I would wait for the refactoring based on the comments provided

**Comment by matozoid** [comment]
@moraispgsi normally PR's get merged when all comments on it are resolved. I hear this PR fixes quite a few problems, so it might be more important to merge it right away and resolve things later. But I see it turned red, so the decision is made - it will wait until next week :-)

**Comment by moraispgsi** [comment]
Yes, It is failing because I added two more tests where it fails in the indentation... trying to fix them before we merge.

**Comment by matozoid** [comment]
No hurry, I've started releasing so it will come next Sunday.

**Comment by moraispgsi** [comment]
I am having trouble with addASecondStatementToExistingMethod test, I think my solution is right and this test is wrong. It's funny because this test is ancient leading back to issue #926. The problem I am facing is that the assertation only considers a portion of the original code. [You can see it in this picture](https://pasteboard.co/I3Ljs5y.png). Am I missing something?

**Comment by moraispgsi** [comment]
PR is back to green but I had to modify the test that I mentioned in the previous comment.

File: javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java [hunk 5]
```diff
@@ -803,7 +803,7 @@ void addASecondStatementToExistingMethod() throws IOException {
         assertEquals("public void someMethod() {" + EOL
                 + "        String test = \"\";" + EOL
                 + "        String test2 = \"\";" + EOL
-                + "}", LexicalPreservingPrinter.print(methodDeclaration));
+                + "    }", LexicalPreservingPrinter.print(methodDeclaration));
```
Comment (ftomassetti) [inline javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java:808]: Mmm, I think that ideally the right brace should not be intended because the opening method was not indented. However that would be really tricky to implement as we should remember where the brace was opened and what indentation we had there

Comment (moraispgsi) [reply javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java:808]: What should we do about it?

Comment (matozoid) [reply javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java:808]: @ftomassetti - what do you think?

Comment (ftomassetti) [reply javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java:808]: We could leave it as it is for now, perhaps adding a comment in the test because if later someone implement the complex but more correct behavior he will break this test

Comment (matozoid) [reply javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java:808]: Okay, @moraispgsi, let's get that comment in and merge this thing.

Comment (moraispgsi) [reply javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java:808]: @matozoid I added the comment.

**Comment by matozoid** [comment]
Thanks for supporting your PR, @moraispgsi !
