### PR TITLE
Fix for #3710 by cutting off resolution loops involving object creation steps.

### LINKED ISSUE #3710: Inner class instantiation statement cause StackOverflowError when trying to resolve method call to the declaration
Consider the following example:

```java
public class JavaParserStackOverflowErrorTest {

    public static Object test(SomeType value) {
        return value.getFoo().getBar().new SomeAnotherType();
    }

}
```

If we try to parse above source with the JavaParser 3.24.4 (latest available version on Maven Central at the time of writing) and then resolve method call chain `value.getFoo().getBar()` to the declaration with the `MethodCallExpr.resolve()` call we will got `StackOverflowError` instead of expected `UnsolvedSymbolException`.

However, if we drop the `.new SomeAnotherType()` part from the source, then we will got `UnsolvedSymbolException` as expected.

Similar result with `com.github.javaparser.ast.expr.Expression::calculateResolvedType()` invocation on the same method call chain.

Quick dig show that *without* inner class instantiation statement type resolution chain will be just

```text
getType on method call value.getFoo()
getType on name expr value
```

In contast, inner class instantiation statement cause infinite loop:

```text
getType on method call value.getFoo()
getType on method call value.getFoo().getBar()
getType on method call value.getFoo()
getType on method call value.getFoo().getBar()
getType on method call value.getFoo()
getType on method call value.getFoo().getBar()
getType on method call value.getFoo()
getType on method call value.getFoo().getBar()
getType on method call value.getFoo()
getType on method call value.getFoo().getBar()
getType on method call value.getFoo()
getType on method call value.getFoo().getBar()
getType on method call value.getFoo()
getType on method call value.getFoo().getBar()
...
```

Here is the reproducer project: https://github.com/Maccimo/JavaParserSOE
Complete source of the above sample for reference: https://github.com/Maccimo/JavaParserSOE/blob/master/src/test/resources/JavaParserStackOverflowErrorTest.java

### PR DESCRIPTION
**Pull request by johanneskloos**
Fixes #3710.
The idea of the fix is that the scope in inner class object creation expressions, e.g., `makeOuter().new Inner()`, can cause resolution loops in just the same way that the scope of a field access or method call can, and should be handled in the same way.

### CODE REVIEW

File: javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java [hunk 1]
```diff
@@ -119,6 +119,7 @@ public final Optional<Context> getParent() {
         // is not the same as the current node.
         while (notMethodNode instanceof MethodCallExpr
                 || notMethodNode instanceof FieldAccessExpr
+                || (notMethodNode instanceof ObjectCreationExpr && notMethodNode.hasScope())
```
Comment (jlerbsc) [inline javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java:128]: I'm not sure that the expression new A().new B() can be solved correctly.

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3710Test.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        CompilationUnit compilationUnit = parser.parse(sourceCode).getResult().get();
+        Optional<MethodCallExpr> methodCall = compilationUnit.findFirst(MethodCallExpr.class);
+
+        ResolvedMethodDeclaration resolvedMethod = methodCall.get().resolve();
+
+        Assertions.assertEquals(
+                "com.github.javaparser.symbolsolver.Outer.make()", resolvedMethod.getQualifiedSignature());
+    }
+}
+
```
Comment (jlerbsc) [inline javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3710Test.java:40]: Please include these classes in the source code to be parsed.

File: javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java (hunk 1 above)
Comment (jlerbsc) [reply javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java:128]: Please add a comment explaining simply and clearly why this has been added

Comment (johanneskloos) [reply javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java:128]: I have added a comment, and a unit test for the case you mentioned.

File: javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3710Test.java (hunk 2 above)
Comment (johanneskloos) [reply javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3710Test.java:40]: done

File: javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java (hunk 1 above)
Comment (johanneskloos) [reply javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/AbstractJavaParserContext.java:128]: In fact, I added two unit tests :)

**Comment by jlerbsc** [comment]
Thank you for your contribution
